{% set name = "gaussiancl" %}
{% set version = "2023.1.post0" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/gaussiancl-{{ version }}.tar.gz
  sha256: 7dc6aacf47b8f981afc50648450e88c83e7c88b689d3304c7da1ff916c0a1815

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - numpy
    - transformcl >=2022.7.28

test:
  imports:
    - gaussiancl
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/cltools/gaussiancl
  summary: angular power spectra for transformed Gaussian random fields
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ntessore
    - paddyroddy
    - Saransh-cpp
